In [7]:
import pandas as pd

dev = pd.read_csv('../data/Restaurant/Test.csv')
dev_ = pd.read_csv('../data/Restaurant/Test_.csv')

In [10]:
dev

,input_raw,input,output,output_raw
0,"quán thoáng rộng, hải sản đa dạng nhưng quán h...","quán thoáng rộng , hải sản đa dạng nhưng quán ...",không gian tốt vì quán thoáng rộng và lựa chọn...,"{AMBIENCE#GENERAL,quán,positive,thoáng rộng}; ..."
1,thịt hơi ít nhưng vị đậm đà nên ăn ưng luôn,thịt hơi ít nhưng vị đậm đà nên ăn ưng luôn,chất lượng đồ ăn tốt vì vị đậm đà và lựa chọn ...,"{FOOD#QUALITY,vị,positive,đậm đà}; {FOOD#STYLE..."
2,"quán ngon, nhân viên dễ thương, tìm hơi khó, k...","quán ngon , nhân viên dễ thương , tìm hơi khó ...",nhà hàng nói chung tốt vì quán ngon và dịch vụ...,"{RESTAURANT#GENERAL,quán,positive,ngon}; {SERV..."
3,giá cả thì cũng khá ổn so với sinh viên như mì...,giá cả thì cũng khá ổn so với sinh viên như mì...,giá tiền nhà hàng tốt vì giá cả khá ổn và dịch...,"{RESTAURANT#PRICES,giá cả,positive,khá ổn}; {S..."
4,giá cả hơi cao tuy nhiên xứng tầm với chất lượ...,giá cả hơi cao tuy nhiên xứng tầm với chất lượ...,dịch vụ tốt vì thái độ phục vụ #tốt và chất lư...,"{SERVICE#GENERAL,thái độ phục vụ,positive,null..."
...,...,...,...,...
578,không gian sang trọng sạch sẽ gt giá cao mà,không gian sang trọng sạch sẽ gt giá cao mà,giá tiền nhà hàng tệ vì giá cao và không gian ...,"{RESTAURANT#PRICES,giá,negative,cao}; {AMBIENC..."
579,đồ ăn chế biến cũng ngon mỗi tội phục vụ thì h...,đồ ăn chế biến cũng ngon mỗi tội phục vụ thì h...,dịch vụ tốt vì nhiều nhân viên dễ thương và ch...,"{SERVICE#GENERAL,nhiều nhân viên,positive,dễ t..."
580,"đồ ăn cũng bình thường, phục vụ siêu chậm , sẽ...","đồ ăn cũng bình thường , phục vụ siêu chậm , s...",dịch vụ tệ vì phục vụ chậm và chất lượng đồ ăn...,"{SERVICE#GENERAL,phục vụ,negative,chậm}; {FOOD..."
581,vị trí ngay mặt đường nên dễ tìm chỗ để xe tho...,vị trí ngay mặt đường nên dễ tìm chỗ để xe tho...,vấn đề khác tốt vì chỗ để xe thoải mái và địa ...,"{RESTAURANT#MISCELLANEOUS,chỗ để xe,positive,t..."
582,quán đông nên bạn nên book trước khi đến giá t...,quán đông nên bạn nên bok trước khi đến giá th...,nhà hàng nói chung tạm vì quán đông và chất lư...,"{RESTAURANT#GENERAL,quán,neutral,đông}; {FOOD#..."

In [11]:
dev_

,input_raw,input,output,output_raw
0,"quán thoáng rộng, hải sản đa dạng nhưng quán h...","quán thoáng rộng , hải sản đa dạng nhưng quán ...","{AMBIENCE#GENERAL,quán,positive,thoáng rộng}; ...","{AMBIENCE#GENERAL,quán,positive,thoáng rộng}; ..."
1,thịt hơi ít nhưng vị đậm đà nên ăn ưng luôn,thịt hơi ít nhưng vị đậm đà nên ăn ưng luôn,"{FOOD#QUALITY,vị,positive,đậm đà}; {FOOD#STYLE...","{FOOD#QUALITY,vị,positive,đậm đà}; {FOOD#STYLE..."
2,"quán ngon, nhân viên dễ thương, tìm hơi khó, k...","quán ngon , nhân viên dễ thương , tìm hơi khó ...","{RESTAURANT#GENERAL,quán,positive,ngon}; {SERV...","{RESTAURANT#GENERAL,quán,positive,ngon}; {SERV..."
3,giá cả thì cũng khá ổn so với sinh viên như mì...,giá cả thì cũng khá ổn so với sinh viên như mì...,"{RESTAURANT#PRICES,giá cả,positive,khá ổn}; {S...","{RESTAURANT#PRICES,giá cả,positive,khá ổn}; {S..."
4,giá cả hơi cao tuy nhiên xứng tầm với chất lượ...,giá cả hơi cao tuy nhiên xứng tầm với chất lượ...,"{SERVICE#GENERAL,thái độ phục vụ,positive,null...","{SERVICE#GENERAL,thái độ phục vụ,positive,null..."
...,...,...,...,...
578,không gian sang trọng sạch sẽ gt giá cao mà,không gian sang trọng sạch sẽ gt giá cao mà,"{RESTAURANT#PRICES,giá,negative,cao}; {AMBIENC...","{RESTAURANT#PRICES,giá,negative,cao}; {AMBIENC..."
579,đồ ăn chế biến cũng ngon mỗi tội phục vụ thì h...,đồ ăn chế biến cũng ngon mỗi tội phục vụ thì h...,"{SERVICE#GENERAL,nhiều nhân viên,positive,dễ t...","{SERVICE#GENERAL,nhiều nhân viên,positive,dễ t..."
580,"đồ ăn cũng bình thường, phục vụ siêu chậm , sẽ...","đồ ăn cũng bình thường , phục vụ siêu chậm , s...","{SERVICE#GENERAL,phục vụ,negative,chậm}; {FOOD...","{SERVICE#GENERAL,phục vụ,negative,chậm}; {FOOD..."
581,vị trí ngay mặt đường nên dễ tìm chỗ để xe tho...,vị trí ngay mặt đường nên dễ tìm chỗ để xe tho...,"{RESTAURANT#MISCELLANEOUS,chỗ để xe,positive,t...","{RESTAURANT#MISCELLANEOUS,chỗ để xe,positive,t..."
582,quán đông nên bạn nên book trước khi đến giá t...,quán đông nên bạn nên bok trước khi đến giá th...,"{RESTAURANT#GENERAL,quán,neutral,đông}; {FOOD#...","{RESTAURANT#GENERAL,quán,neutral,đông}; {FOOD#..."